apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-test
  name: api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-test
  strategy: {}
  template:
    metadata:
      labels:
        app: api-test
    spec:
      containers:
      - image: davidk1rby/docker_api_test:1.0.0
        name: docker-api-test-tkj6s
        ports:
        - containerPort: 5000
        resources: {}
status: {}
